export * from "./coordsType"
export * from "./cellDataType"
export * from "./errorInterface"
export * from "./socketDataInterface"
export * from "./socketErrorInterface"
export * from "./errorMsgType"